### DISCUSSION TITLE
Need help in deployment

### DISCUSSION THREAD

**Discussion by talhaanwarch** [ToolJet/ToolJet#7054] [Q&A] [answered]
Hi. I am able to run tooljet locally , but when i tried to run it on server. 
I got this
```
wait-for-it.sh: waiting 300 seconds for $POSTGRES_HOST:$POSTGRES_PORT
wait-for-it.sh: timeout occurred after waiting 300 seconds for $POSTGRES_HOST:$POSTGRES_PORT
wait-for-it.sh: strict mode, refusing to execute subprocess
```

I am using TOOLJET_HOST=http://localhost:80 both in production and local environment. I am not what is the issue. Can any one assist

This is docker-compose file
```
version: '3'

services:
  tooljet:
    tty: true
    stdin_open: true
    image: tooljet/tooljet-ce:latest
    #restart: always
    env_file: .env
    ports:
      - 8005:80
    environment:
      SERVE_CLIENT: "true"
      PORT: "80"
    command: npm run start:prod
    networks:
      - milvus

networks:
  milvus:
    external: true
    
 ```
 
 Another docker-compose file
 ```
 version: '3.5'
services:
  app:
    build: .
    ports:
    env_file:
      - .env
    networks:
      - milvus

  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    volumes:
      - sqldb:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - milvus

volumes:
  sqldb:

networks:
  milvus:
    external: true
 ``` 
    
Here is .env

```
POSTGRES_DB=postgres
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
POSTGRES_PORT=5432
POSTGRES_HOST=postgres

TOOLJET_HOST=http://localhost:80
#https://docs.tooljet.com/docs/setup/env-vars/
LOCKBOX_MASTER_KEY=
SECRET_KEY_BASE=
##DATABASE CONFIG
ORM_LOGGING=all
# Reusing the PostgreSQL values
# I dont know if there is a way to handle this
PG_DB=$POSTGRES_DB
PG_USER=$POSTGRES_USER
PG_HOST=$POSTGRES_HOST
PG_PASS=$POSTGRES_PASSWORD
PG_PORT=$POSTGRES_PORT
```
