### ISSUE TITLE
Tooljet Docker Migration Loop: Repeated `LockMigrationsTable...` Migration Prevents Server Startup

### ISSUE THREAD

**Issue by ardamaks** [ToolJet/ToolJet#13001]
### Summary

When running Tooljet via the official Docker image and Docker Compose, the server is stuck in a migration loop. The migration system repeatedly runs a migration named `LockMigrationsTable...`, deletes and reinserts it, and never starts the web server. This makes the service unusable.

---

### Environment

- **Tooljet Docker image:** `tooljet/tooljet-ce:latest` (also tested `v3.14.0` and `ce-lts-latest`)
- **Postgres version:** 13 (official Docker image)
- **Postgres port:** 5432 (default, no overrides)
- **Deployment:** Docker Compose, official entrypoint, `.env` file for configuration

---

### Steps to Reproduce

1. Deploy Tooljet with the official Docker Compose and Docker image.
2. Wait for the container to start.
3. Observe logs: the migration system always detects a new migration (`LockMigrationsTable...`), deletes and reinserts it, and never starts the server.
4. Running migrations manually inside the container (with proper network and working directory) produces the same loop.

---

### What I Have Tried

- Verified all environment variables and port settings (always 5432).
- Inspected Docker Compose and `.env` for misconfiguration — none found.
- Removed/recreated database volume for a fresh start — issue persists.
- Ran migrations manually inside the container — loop persists.
- Searched local codebase for `LockMigrationsTable` logic — not present, appears bundled in Docker image.
- Attempted to inspect the `migrations` table (logs confirm repeated deletion/insertion of the lock migration).
- Found a related issue for non-5432 ports, but I am using the default port.

---

### Logs

```
query: SELECT * FROM "migrations" "migrations" ORDER BY "id" DESC
161 migrations are already loaded in the database.
93 migrations were found in the source code.
PopulateManualConnectionTypeForOldPostgresDs1731283187529 is the last executed migration. It was executed on Sun Nov 10 2024 23:59:47 GMT+0000 (Coordinated Universal Time).
1 migrations are new migrations must be executed.
query: START TRANSACTION
query: DELETE FROM migrations where name = 'LockMigrationsTable1234567890000'
query: LOCK TABLE migrations;
query: INSERT INTO "migrations"("timestamp", "name") VALUES ($1, $2) -- PARAMETERS: [1234567891000,"LockMigrationsTable1234567891000"]
Migration LockMigrationsTable1234567891000 has been  executed successfully.
query: COMMIT
```
This cycle repeats indefinitely.

---

### Impact

- Tooljet cannot start or serve requests.
- Workaround is to exclude Tooljet from the stack until a fix is available.

---

### Request

- Please investigate the migration logic for the repeated `LockMigrationsTable` migration.
- Is there a workaround or patch available?
- Can you clarify if this is a regression or a new bug in recent images?

**Comment by slancerk** [comment]
Could you please confirm if `command: npm run start:prod` is present in your docker-compose file under service tooljet?
For your reference, here's a sample tooljet service configuration:

```
tooljet:
    tty: true
    stdin_open: true
    container_name: Tooljet-app
    image: tooljet/tooljet:ee-lts-latest
    restart: always
    env_file: .env
    ports:
      - 80:80
    deploy: # Please adjust the resource according to your usecase
      resources:
        limits:
          cpus: '1'
          memory: 2G
    depends_on:
      - postgres
    environment:
      SERVE_CLIENT: "true"
      PORT: "80"
    command: npm run start:prod
```
If this line is not there in your docker-compose file you might face this loop issue.
