### ISSUE TITLE
ToolJet Dashboard does not show any content!?

### ISSUE THREAD

**Issue by nicoleonwien** [ToolJet/ToolJet#2293]
### Version Information
1.1.0

### Environment
Docker

### What is the expected behaviour?
 I should be able to access my dashboard normally because I just installed ToolJet over Docker.

### What is the current behaviour?
I start my ToolJet via Docker Compose. There are no errors at startup. But when I try to call the Dashboard. It only gives me a background color of the ToolJet Dashboard but nothing else.

### How to reproduce the issue?

1. Every time I start ToolJet via Docker Compose

### Screenshots or Screencast
![Screenshot](https://user-images.githubusercontent.com/78145904/154755815-caf7f03f-950a-40f4-82fd-72bb7773d37f.png)

### docker-compose.yaml file

```
version: "3"
services:
  plugins:
    build:
      context: ./
      dockerfile: ./docker/plugins.Dockerfile.dev
    image: tooljet-plugins:development
    platform: linux/x86_64
    volumes:
      - ./plugins:/app/plugins
    command: npm run --prefix plugins start
    networks:
      abslm-network:
        ipv4_address: 10.100.0.11

  client:
    build:
      context: ./
      dockerfile: ./docker/client.Dockerfile.dev
    image: tooljet-client:development
    platform: linux/x86_64
    volumes:
      - ./frontend:/app/frontend:delegated
      - ./plugins:/app/plugins
      - /app/frontend/node_modules/
    ports:
      - 8082:8082
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
      - NODE_ENV=development
    command: npm run --prefix frontend start
    networks:
      abslm-network:
        ipv4_address: 10.100.0.12

  server:
    build:
      context: ./
      dockerfile: ./docker/server.Dockerfile.dev
    image: tooljet-server:development
    platform: linux/x86_64
    volumes:
      - ./server:/app/server:delegated
      - ./plugins:/app/plugins
      - /app/server/node_modules/
      - ./.env:/app/.env
      - ./.env.test:/app/.env.test
    ports:
      - 28591:3000
    environment:
      - SERVE_CLIENT=false
      - FORCE_COLOR=1
    command: npm run --prefix server start:dev
    networks:
      abslm-network:
        ipv4_address: 10.100.0.14

networks:
  abslm-network:
    external: true
    name: abslm-network
```

### .env file

```
# Create .env from this example file and replace values for the environment.
# The application expects a separate .env.test for test environment configuration
# Get detailed information about each variable here: https://docs.tooljet.com/docs/deployment/env-vars

TOOLJET_HOST=http://localhost:8082
LOCKBOX_MASTER_KEY=
SECRET_KEY_BASE=

## Configure a hostname for the server
# SERVER_HOST=

# DATABASE CONFIG
ORM_LOGGING=error
PG_DB=tooljet
PG_USER=
PG_HOST=10.100.0.10
PG_PASS=

# Checks every 24 hours to see if a new version of ToolJet is available
# (Enabled by default. Set 0 to disable)
CHECK_FOR_UPDATES=0

# Checks every 24 hours to update app telemetry data to ToolJet hub.
# (Telemetry is enabled by default. Set value to true to disable.)
# DISABLE_APP_TELEMETRY=false

# GOOGLE_CLIENT_ID=
# GOOGLE_CLIENT_SECRET=

# EMAIL CONFIGURATION
DEFAULT_FROM_EMAIL=tooljet@abslm.nl
SMTP_USERNAME=tooljet@abslm.nl
SMTP_PASSWORD=
SMTP_DOMAIN=
SMTP_PORT=465

# DISABLE USER SIGNUPS (true or false). Default: true
DISABLE_SIGNUPS=true

# OBSERVABILITY
# APM_VENDOR=
# SENTRY_DNS=
# SENTRY_DEBUG=

# FEATURE TOGGLE
# COMMENT_FEATURE_ENABLE=

#SSO
# SSO_DISABLE_SIGNUP=
# SSO_RESTRICTED_DOMAIN=
# SSO_GOOGLE_OAUTH2_CLIENT_ID=
# SSO_GIT_OAUTH2_CLIENT_ID=
# SSO_GIT_OAUTH2_CLIENT_SECRET=
```
