### ISSUE TITLE
tooljet/tooljet-ce:v1.2.1 runs a loop db:create

### ISSUE THREAD

**Issue by adtiki01** [ToolJet/ToolJet#2357]
I am running tooljet-ce:v1.2.1 in a docker-compose file. The database is postgres:11.4

After I bring up tooljet client, it seems to go in a loop to perform a db:create

-------- Start of client docker-log --------------------

> @ db:create /app
> npm --prefix server run db:create

> server@0.0.1 db:create /app/server
> ts-node ./scripts/create-database.ts

/app/.env file not found to create database
Picking up config from the environment
database "tooljet" already exists

> @ db:migrate /app
> npm --prefix server run db:migrate

> server@0.0.1 db:migrate /app/server
> ts-node -r tsconfig-paths/register --transpile-only ./node_modules/typeorm/cli.js migration:run

-------- End of client docker-log --------------------

I have already run the command to seed the database and seems to have done it successfully, using the following command:
docker-compose -f docker-compose-tooljet.yml run server npm run db:seed

The server comes up fine:

-------- Start of server docker-log --------------------

> @ start:prod /app
> npm --prefix server run start:prod

> server@0.0.1 start:prod /app/server
> NODE_ENV=production node dist/src/main

Unable to fetch database config from env file for environment: production
Picking up config from the environment
Initializing ToolJet server modules 📡
Initialized ToolJet server, waiting for requests 🚀
Listening on port 3000
{"level":50,"time":1645914931979,"pid":94,"hostname":"407c9445ee18","errno":-2,"code":"ENOENT","syscall":"stat","path":"/app/frontend/build/index.html","expose":false,"statusCode":404,"status":404,"stack":"Error: ENOENT: no such file or directory, stat '/app/frontend/build/index.html'","type":"Error","msg":"ENOENT: no such file or directory, stat '/app/frontend/build/index.html'"}

-------- End of server docker-log --------------------

I am running this behind traefik (here's my docker-compose file)
```

version: '3'

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  tooljet:
    container_name: tooljet
    tty: true
    stdin_open: true
    image: tooljet/tooljet-ce:v1.2.1
    restart: unless-stopped
    env_file: .env-tooljet.txt
    depends_on:
      - server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/tooljet/logs:/var/log/openresty/
      - $PWD/tooljet/certs:/etc/resty-auto-ssl/
      - $PWD/tooljet/fallbackcerts:/etc/fallback-certs
    networks:
      - internal
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.tooljet.loadbalancer.server.port=8082" 
      - "traefik.http.routers.tooljet.rule=Host(`tooljet.xxxx.com`)"
      - "traefik.http.routers.tooljet.tls=true"
      - "traefik.http.routers.tooljet.tls.certresolver=leresolver"
     command: openresty -g "daemon off;"

  server:
    image: tooljet/tooljet-server-ce:v1.2.1
    container_name: tooljetsvr
    tty: true
    stdin_open: true
    restart: unless-stopped
    networks:
      - internal
      - proxy
    env_file: .env-tooljet.txt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.tooljetsvr.loadbalancer.server.port=3000"
      - "traefik.http.routers.tooljetsvr.rule=Host(`tooljetsvr.xxxx.com`)"
      - "traefik.http.routers.tooljetsvr.tls=true"
      - "traefik.http.routers.tooljetsvr.tls.certresolver=leresolver"
    environment:
      SERVE_CLIENT: "true"
      #SERVE_CLIENT: "false"
    command: npm run start:prod
volumes:
  certs:
  logs:
  fallbackcerts:

```

My .env file looks like this:

```

TOOLJET_SERVER_URL=https://tooljetsvr.xxxx.com
TOOLJET_HOST=https://tooljet.xxxx.com
LOCKBOX_MASTER_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
SECRET_KEY_BASE=yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy

# DATABASE CONFIG
ORM_LOGGING=
PG_DB=tooljet
PG_USER=user
PG_HOST=postgres
PG_PASS=secret-password

# Checks every 24 hours to see if a new version of ToolJet is available
CHECK_FOR_UPDATES=check_if_updates_are_available

```

Traefik is able to route to the client. But comes up with "Bad Gateway" - which usually means that the application is not responding correctly.

Please let me know how I can set it up correctly.

Thanks
