### ISSUE TITLE
Unable to start Tooljet - Error: failed with status code 500

### ISSUE THREAD

**Issue by arsaboo** [ToolJet/ToolJet#3016]
### Version Information
Latest docker release 
### Environment
Tooljet using the following docker-compose
```
version: '3'

services:
  client:
    tty: true
    stdin_open: true
    container_name: tooljet_client
    image: tooljet/tooljet-client-ce:latest
    restart: always
    env_file: .env
    depends_on:
      - server
    volumes:
      - logs:/var/log/openresty/
      - certs:/etc/resty-auto-ssl/
      - fallbackcerts:/etc/fallback-certs
    ports:
      - 8082:80
      - 8443:443
    command: openresty -g "daemon off;"

  server:
    image: tooljet/tooljet-server-ce:latest
    tty: true
    stdin_open: true
    container_name: tooljet_server
    restart: always
    ports:
      - 3000
    env_file: .env
    environment:
      SERVE_CLIENT: "true"
    command: npm run start:prod
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    container_name: tooljet_postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/docker/containers/tooljet/db
  certs:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/docker/containers/tooljet/certs  
  logs:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/docker/containers/tooljet/logs  
  fallbackcerts:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /mnt/docker/containers/tooljet/fallbackcerts  
```

### What is the current behaviour?
Tooljet is not starting up. Here is the errorI am seeing in the server logs. 

{"level":30,"time":1652120785888,"pid":99,"hostname":"c6d6ddd7b7f7","req":{"id":173,"method":"GET","url":"/api/organizations/public-configs","query":{},"params":{"0":"/organizations/public-configs"},"headers":{"host":"192.168.2.188","connection":"close","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36","dnt":"1","content-type":"application/json","accept":"*/*","referer":"http://192.168.2.188:8082/login?redirectTo=/","accept-encoding":"gzip, deflate","accept-language":"en-US,en;q=0.9","cookie":"WT2_SESSION=c92094559c68f296004e75cb60b88beb; csrftoken=ghF6XrNwRSM4qP4WO3zXdpSUGmIEISQar8oXhxnYgzHbDoQ24pOUEJIBvrpELVyC; PHPSESSID=064763002e5cff838740628702bc0dff"},"remoteAddress":"172.18.0.4","remotePort":43820},"res":{"statusCode":500,"headers":{"x-powered-by":"Express","access-control-allow-origin":"*","content-security-policy":"img-src * data:;script-src maps.googleapis.com apis.google.com accounts.google.com 'self' 'unsafe-inline' 'unsafe-eval' blob:;default-src maps.googleapis.com apis.google.com accounts.google.com *.sentry.io 'self' blob:;connect-src ws://localhost 'self' *;frame-ancestors *;frame-src *;base-uri 'self';block-all-mixed-content;font-src 'self' https: data:;object-src 'none';script-src-attr 'none';style-src 'self' https: 'unsafe-inline'","content-type":"application/json; charset=utf-8","content-length":"151","etag":"W/\"97-NOACGzT1jMM33V4GJA5QlITJ5zA\""}},"err":{"type":"Error","message":"failed with status code 500","stack":"Error: failed with status code 500\n    at ServerResponse.onResFinished (/app/server/node_modules/pino-http/logger.js:77:38)\n    at ServerResponse.clsBind (/app/server/node_modules/cls-hooked/context.js:172:17)\n    at ServerResponse.emit (events.js:387:35)\n    at ServerResponse.emit (domain.js:532:15)\n    at ServerResponse.emitted (/app/server/node_modules/emitter-listener/listener.js:134:21)\n    at onFinish (_http_outgoing.js:792:10)\n    at callback (internal/streams/writable.js:513:21)\n    at afterWrite (internal/streams/writable.js:466:5)\n    at afterWriteTick (internal/streams/writable.js:453:10)\n    at processTicksAndRejections (internal/process/task_queues.js:81:21)"},"responseTime":5,"msg":"request errored"}

query: SELECT DISTINCT "distinctAlias"."Organization_id" as "ids_Organization_id" FROM (SELECT "Organization"."id" AS "Organization_id", "Organization"."name" AS "Organization_name", "Organization"."domain" AS "Organization_domain", "Organization"."enable_sign_up" AS "Organization_enable_sign_up", "Organization"."created_at" AS "Organization_created_at", "Organization"."updated_at" AS "Organization_updated_at", "Organization__ssoConfigs"."id" AS "Organization__ssoConfigs_id", "Organization__ssoConfigs"."organization_id" AS "Organization__ssoConfigs_organization_id", "Organization__ssoConfigs"."sso" AS "Organization__ssoConfigs_sso", "Organization__ssoConfigs"."configs" AS "Organization__ssoConfigs_configs", "Organization__ssoConfigs"."enabled" AS "Organization__ssoConfigs_enabled", "Organization__ssoConfigs"."created_at" AS "Organization__ssoConfigs_created_at", "Organization__ssoConfigs"."updated_at" AS "Organization__ssoConfigs_updated_at" FROM "organizations" "Organization" LEFT JOIN "sso_configs" "Organization__ssoConfigs" ON "Organization__ssoConfigs"."organization_id"="Organization"."id") "distinctAlias" ORDER BY "Organization_id" ASC LIMIT 1

{"level":50,"time":1652120786018,"pid":99,"hostname":"c6d6ddd7b7f7","req":{"id":174,"method":"GET","url":"/api/organizations/public-configs","query":{},"params":{"0":"/organizations/public-configs"},"headers":{"host":"192.168.2.188","connection":"close","user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36","dnt":"1","content-type":"application/json","accept":"*/*","referer":"http://192.168.2.188:8082/login?redirectTo=/","accept-encoding":"gzip, deflate","accept-language":"en-US,en;q=0.9","cookie":"WT2_SESSION=c92094559c68f296004e75cb60b88beb; csrftoken=ghF6XrNwRSM4qP4WO3zXdpSUGmIEISQar8oXhxnYgzHbDoQ24pOUEJIBvrpELVyC; PHPSESSID=064763002e5cff838740628702bc0dff"},"remoteAddress":"172.18.0.4","remotePort":43822},"stack":"TypeError: Cannot read property 'id' of undefined\n    at OrganizationsController.getOrganizationDetails (/app/server/dist/src/controllers/organizations.controller.js:53:88)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async /app/server/node_modules/@nestjs/core/router/router-execution-context.js:46:28\n    at async /app/server/node_modules/@nestjs/core/router/router-proxy.js:9:17","type":"Error","msg":"Cannot read property 'id' of undefined"}
