### ISSUE TITLE
Showing "Unable to fetch notifications" alerts whenever the page changes

### ISSUE THREAD

**Issue by tunix** [ToolJet/ToolJet#4544]
### Version Information

tooljet-ce
v1.27.4

### Environment

Kubernetes

### What is the expected behaviour?

No such alert to show up.

### What is the current behaviour?

An alert with `Unable to fetch notifications` as content is shown whenever I change to another page, refresh the page etc.

### How to reproduce the issue?

1. Created a PostgreSQL database
2. Deployed tooljet-ce on k8s
3. deployment.yaml:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tooljet
spec:
  progressDeadlineSeconds: 300
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    spec:
      containers:
        - name: tooljet
          image: tooljet/tooljet-ce
          args: ["npm", "run", "start:prod"]
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: LOCKBOX_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: tooljet
                  key: lockbox_key
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: tooljet
                  key: secret_key_base
            - name: PG_HOST
              valueFrom:
                secretKeyRef:
                  name: tooljet
                  key: pg_host
            - name: PG_DB
              valueFrom:
                secretKeyRef:
                  name: tooljet
                  key: pg_db
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: tooljet
                  key: pg_user
            - name: PG_PASS
              valueFrom:
                secretKeyRef:
                  name: tooljet
                  key: pg_pass
            - name: PG_DB_OWNER
              value: "false"
            - name: COMMENT_FEATURE_ENABLE
              value: "false"
            - name: DISABLE_MULTI_WORKSPACE
              value: "false"
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
              scheme: HTTP
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          resources:
            limits:
              cpu: 2000m
              memory: 2000Mi
            requests:
              cpu: 1000m
              memory: 1000Mi
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 15
      serviceAccountName: tooljet-sa
```

### Screenshots or Screencast

![image](https://user-images.githubusercontent.com/47731/196999778-643b713e-a853-4901-bb48-77fce2ce5b8a.png)

### Please provide any traces or logs that could help here.

There are no logs inside the console nor any failed network transactions.
