### ISSUE TITLE
Error at Docker Startup (Migration commit)

### ISSUE THREAD

**Issue by luizeof** [ToolJet/ToolJet#5017]
### Version Information

latest image

### Environment

Docker

### What is the expected behaviour?

Entrypoint runs whitout exit;

### What is the current behaviour?

Entrypoint runs the migrations and apparently when a migration fails, the service does exit 0.

### How to reproduce the issue?

1. Start an Docker Stack
2. Wait for Migrations
3. Migration stops after commit

### Screenshots or Screencast

![a542df72-5ce5-498a-a425-d7da4ec9a0de](https://user-images.githubusercontent.com/257004/208458594-b89210e7-1709-4771-a749-8e5ee34a74a4.png)

![cd16f05c-4708-4402-9b37-2e8c4aecf562](https://user-images.githubusercontent.com/257004/208458628-7db22e6d-1292-485f-867c-0f1d35e77030.png)

**Comment by luizeof** [comment]
@Navaneeth-pk Were you able to reproduce the error?

**Comment by withshubh** [comment]
Hey @luizeof - Thanks for creating the issue. 🙌 We will take a look at it and let you know.
You can also join our [Community Slack here](https://www.tooljet.com/slack).

**Comment by ChrisChris15** [comment]
I am also getting the same error with the 77/49 and 77/31 migrations. the log shows those 2 errors continuously looping.

**Comment by akshaysasidrn** [comment]
Could you folks please share which type of setup is being done? Is this a docker-compose setup?
In the screenshot attached, the migration has run successfully. The container should then boot up with `npm run start:prod` command as a part of its entrypoint. Please check if that is provided and if yes, do check if there is any throttle on cpu/mem resources allocated to the container.

**Comment by n1xn** [comment]
same here using compose

```
  tooljet:
    image: tooljet/tooljet-ee:latest
    container_name: ${COMPOSE_PROJECT_NAME}_tooljet
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@postgres:5432/tooljet?sslmode=disable
      - SECRET_KEY_BASE=57a7664ae2ef892d7d0632201f64c149fa5f040b5234a2d7670969ff06d185f9 #32 byte hex
      - LOCKBOX_MASTER_KEY=932777d78044641b5208a58429e52f363174c2991571776e778b795413005611 #64 byte hex
    ports:
      - '6000:80'
    networks:
      - backend
    depends_on:
      - postgres
```
