### ISSUE TITLE
`DB_HOST` is not getting introspected by the `DATABASE_URL` environment variable

### ISSUE THREAD

**Issue by rhuanbarreto** [ToolJet/ToolJet#5749]
### Version Information
Latest

### Environment
Tooljet on Docker

### What is the expected behaviour?
Given that the `DATABASE_URL` environment variable is set, there's no need to declare `PG_` variables once they come from the previous one. But at startup, I get an error:

```
tooljet-tooljet-1    | Error: you need to provide a host and port to test.
tooljet-tooljet-1    | Usage:
tooljet-tooljet-1    |     wait-for-it.sh host:port [-s] [-t timeout] [-- command args]
tooljet-tooljet-1    |     -h HOST | --host=HOST       Host or IP under test
tooljet-tooljet-1    |     -p PORT | --port=PORT       TCP port under test
tooljet-tooljet-1    |                                 Alternatively, you specify the host and port as host:port
tooljet-tooljet-1    |     -s | --strict               Only execute subcommand if the test succeeds
tooljet-tooljet-1    |     -q | --quiet                Don't output any status messages
tooljet-tooljet-1    |     -t TIMEOUT | --timeout=TIMEOUT
tooljet-tooljet-1    |                                 Timeout in seconds, zero for no timeout
tooljet-tooljet-1    |     -- COMMAND ARGS             Execute command with args after the test finishes
tooljet-tooljet-1 exited with code 1
```

### How to reproduce the issue?

This doesn't work:

```
version: '3'

services:
  tooljet:
    image: tooljet/tooljet-ce:latest
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres1/postgres
    command: npm run start:prod
  postgres1:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
```

This works:

```
version: '3'

services:
  tooljet:
    image: tooljet/tooljet-ce:latest
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres1/postgres
      PG_HOST: postgres1
    command: npm run start:prod
  postgres1:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
```

### Any possible solutions?

Adjusting https://github.com/ToolJet/ToolJet/blob/6a60e95faabc57365010f1b515d824afdac180da/server/ormconfig.ts#LL22C20-L22C20 to consider DATABASE_URL instead.

### If the bug is confirmed, would you be willing to submit a PR?

Yes. Will need guidance on how to run it.
