### ISSUE TITLE
`TOOLJET_DB_*` vars don't support SSL connections

### ISSUE THREAD

**Issue by rhuanbarreto** [ToolJet/ToolJet#5768]
### Version Information

Any

### Environment

Self Hosted Tooljet in Azure. But it can be with any DB that doesn't support unencrypted connections.

### What is the expected behaviour?

It was expected to have a similar environment variable like `DATABASE_URL` to set the Tooljet DB address to support SSL.

### What is the current behaviour?

Connection fails with error message:

> relation "public.{uuid}" does not exist

### How to reproduce the issue?

Docker compose file for an Azure Postgres Server:

```
services:
  tooljet:
    image: tooljet/tooljet-ce:latest
    ports:
      - 3000:3000
    environment:
      # Base Config
      TOOLJET_HOST: http://localhost:3000
      LOCKBOX_MASTER_KEY: {masterkey}
      SECRET_KEY_BASE: {secretkey}
      # Database Config
      PG_DB: tooljet_production
      PG_USER: {username}
      PG_HOST: {servername}.postgres.database.azure.com
      PG_PASS: {password}
      PG_PORT: "5432"
      DATABASE_URL: postgres://{username}:{password}@{servername}.postgres.database.azure.com/tooljet_production?sslmode=require
      # Tooljet DB
      ENABLE_TOOLJET_DB: "true"
      PGRST_JWT_SECRET: {jwtsecret}
      PGRST_HOST: http://postgrest:3000
      TOOLJET_DB: tooljet_db
      TOOLJET_DB_HOST: {servername}.postgres.database.azure.com
      TOOLJET_DB_USER: {username}
      TOOLJET_DB_PASS: {password}
      TOOLJET_DB_PORT: "5432"
      # Feature flags
      COMMENT_FEATURE_ENABLE: "true"
      ENABLE_MULTIPLAYER_EDITING: "true"
      ENABLE_MARKETPLACE_FEATURE: "true"
      DISABLE_TOOLJET_TELEMETRY: "true"
      ORM_LOGGING: "true"
    command: npm run start:prod
  postgrest:
    image: postgrest/postgrest:v10.1.1.20221215
    restart: always
    environment:
      PGRST_DB_URI: postgres://{username}:{password}@{servername}.postgres.database.azure.com/tooljet_db?sslmode=require
      PGRST_JWT_SECRET: {jwtsecret}
      PGRST_LOG_LEVEL: info
```

### Any possible solutions?

Implement better handling of SSL as an environment variable.

### Can you identify the location in the driver source code where the problem exists?

https://github.com/ToolJet/ToolJet/blob/45cd637bde69cdb8f52682fb3cba30fe135854c4/server/ormconfig.ts#L56-L68
