### ISSUE TITLE
The deployment with something wrong?

### ISSUE THREAD

**Issue by shuiiiiiimu** [ToolJet/ToolJet#643]
### Environment

MacOS 
Docker version 20.10.7, build f0df350
docker-compose version 1.29.2, build 5becea4c

### What is the expected behaviour?

  run ToolJet, and visit URL on browser.

### What is the current behaviour?

  It seems that there is no problem, but can not visit URL on browser.

### docker-compose.yaml

```yaml
version: '3'

services:
  server:
    image: tooljet/tooljet-ce:latest
    tty: true
    stdin_open: true
    restart: always
    depends_on:
      - pg_db
    links:
      - pg_db
    ports:
      - 3000
    environment:
      RAILS_ENV: "production"
      PG_DB: "tooljet"
      PG_USER: "postgres"
      PG_HOST: "pg_db"
      PG_PORT: "5432"
      PG_PASS: "postgres"
      ORM_LOGGING: "all"
      TOOLJET_HOST: "http://tj.xxxxx.top:3000"
      LOCKBOX_MASTER_KEY: "65813374e8faa9f232f5ea5fabbda5ce9c565e4f91a6f0f29ea190c90e526a0b"
      SECRET_KEY_BASE: "02004601ef89c330cfccd9439bb4533c11056aee31124da5b070c123fd4aee1f581c23a6e4ad8c444badd673cce3f86a016bf23810d58929ea9bcb6c7d6512d9"
    command: npm run --prefix server start:prod

  pg_db:
    image: postgres:13
    restart: always
    ports:
      - 5432
    volumes:
      - postgres:/data/postgres
    environment:
      - POSTGRES_PASSWORD=postgres

volumes:
  postgres:
```
