### ISSUE TITLE
Flickering issue in ToolJet database

### ISSUE THREAD

**Issue by Nandinisaha13** [ToolJet/ToolJet#6475]
### What is the expected behaviour?
The flickering should not happen while the user wants to edit the table or wants to delete the table.

### What is the current behaviour?
The flickering is happening while the user wants to edit the table or wants to delete the table.

### How to reproduce the issue?

1. Go to database.
2. Create a table.
3. Click on ellipses(edit & delete button is displayed).
4. Observe.

https://github.com/ToolJet/ToolJet/assets/41302917/47980559-84f6-4d05-ae27-d131d4e41507

**Comment by FourAndHalf** [comment]
I looked into it and think the bug is caused due to styling in *themes.scss* file

```scss
.table-list-items#popover-contained {
  .popover-body {
    outline: 1px solid var(--slate3);
    background: var(--base);
    overflow: hidden;
  }
}
```

Most probably it would be wrong, just commented to see what change was needed when the bug gets fixed
