### ISSUE TITLE
Documentation issue about Docker compose deployment and Postgres

### ISSUE THREAD

**Issue by feczo** [ToolJet/ToolJet#856]
https://docs.tooljet.io/docs/deployment/docker/
page says "You should setup a PostgreSQL database manually to be used by the ToolJet server."

This instruction led me to believe to have a local host installation and did not blend well with docker deployment and compose file provided on the page which is
https://raw.githubusercontent.com/ToolJet/ToolJet/main/deploy/docker/docker-compose.yaml

Suggested fix:
replace / update the compose file with something like 

```
version: '3'

services:
  client:
    tty: true
    stdin_open: true
    image: tooljet/tooljet-client-ce:latest
    restart: always
    depends_on:
      - server
    volumes:
      - logs:/var/log/openresty/
      - certs:/etc/resty-auto-ssl/
      - fallbackcerts:/etc/fallback-certs
    ports:
      - 80:80
      - 443:443
    command: openresty -g "daemon off;"

  server:
    image: tooljet/tooljet-server-ce:latest
    tty: true
    stdin_open: true
    restart: always
    ports:
      - 3000
    depends_on:
      - database
    env_file: .env
    environment:
      SERVE_CLIENT: "false"
    command: npm run start:prod

  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - 5432:5432

volumes:
  certs:
  logs:
  fallbackcerts:
  database-data: # named volumes can be managed easier using docker-compose
```

and database.env 

```
POSTGRES_USER=
POSTGRES_PASSWORD=
POSTGRES_DB=
```

and remove instructions to install Postgres manually.
